
// reference data for cross currency conversion
export const CROSS_VIA_MARTIX = [
    { base:'AUD', terms: [{ccy:'AUD', relation:'1:1'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'USD'}, {ccy:'DKK', relation:'USD'}, {ccy:'EUR', relation:'USD'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'USD'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'DDD'}]},
    { base:'CAD', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'1:1'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'USD'}, {ccy:'DKK', relation:'USD'}, {ccy:'EUR', relation:'USD'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'USD'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'DDD'}]},
    { base:'CNY', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'1:1'}, {ccy:'CZK', relation:'USD'}, {ccy:'DKK', relation:'USD'}, {ccy:'EUR', relation:'USD'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'USD'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'INV'}]},
    { base:'CZK', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'1:1'}, {ccy:'DKK', relation:'EUR'}, {ccy:'EUR', relation:'INV'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'EUR'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'EUR'}]},
    { base:'DKK', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'EUR'}, {ccy:'DKK', relation:'1:1'}, {ccy:'EUR', relation:'INV'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'EUR'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'EUR'}]},
    { base:'EUR', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'DDD'}, {ccy:'DKK', relation:'DDD'}, {ccy:'EUR', relation:'1:1'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'DDD'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'DDD'}]},
    { base:'GBP', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'USD'}, {ccy:'DKK', relation:'USD'}, {ccy:'EUR', relation:'USD'}, {ccy:'GBP', relation:'1:1'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'USD'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'DDD'}]},
    { base:'JPY', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'USD'}, {ccy:'DKK', relation:'USD'}, {ccy:'EUR', relation:'USD'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'1:1'}, {ccy:'NOK', relation:'USD'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'INV'}]},
    { base:'NOK', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'EUR'}, {ccy:'DKK', relation:'EUR'}, {ccy:'EUR', relation:'INV'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'1:1'}, {ccy:'NZD', relation:'USD'}, {ccy:'USD', relation:'EUR'}]},
    { base:'NZD', terms: [{ccy:'AUD', relation:'USD'}, {ccy:'CAD', relation:'USD'}, {ccy:'CNY', relation:'USD'}, {ccy:'CZK', relation:'USD'}, {ccy:'DKK', relation:'USD'}, {ccy:'EUR', relation:'USD'}, {ccy:'GBP', relation:'USD'}, {ccy:'JPY', relation:'USD'}, {ccy:'NOK', relation:'USD'}, {ccy:'NZD', relation:'1:1'}, {ccy:'USD', relation:'DDD'}]},
    { base:'USD', terms: [{ccy:'AUD', relation:'INV'}, {ccy:'CAD', relation:'INV'}, {ccy:'CNY', relation:'DDD'}, {ccy:'CZK', relation:'EUR'}, {ccy:'DKK', relation:'EUR'}, {ccy:'EUR', relation:'INV'}, {ccy:'GBP', relation:'INV'}, {ccy:'JPY', relation:'DDD'}, {ccy:'NOK', relation:'EUR'}, {ccy:'NZD', relation:'INV'}, {ccy:'USD', relation:'1:1'}]},
]

export const CURRENCY_DISPLAY = [
    {ccy: 'USD', decimals:2, symbol:'$',   flag:'country/USD.png'}, 
    {ccy: 'AUD', decimals:2, symbol:'$',   flag:'country/AUD.png'}, 
    {ccy: 'CAD', decimals:2, symbol:'$',   flag:'country/CAD.png'},
    {ccy: 'CNY', decimals:2, symbol:'¥',   flag:'country/CNY.png'}, 
    {ccy: 'CZK', decimals:2, symbol:'Kč',  flag:'country/CZK.png'}, 
    {ccy: 'DKK', decimals:2, symbol:'kr',  flag:'country/DKK.png'}, 
    {ccy: 'EUR', decimals:2, symbol:'€',   flag:'country/EUR.png'}, 
    {ccy: 'GBP', decimals:2, symbol:'£',   flag:'country/GBP.png'}, 
    {ccy: 'JPY', decimals:0, symbol:'¥',   flag:'country/JPY.png'}, 
    {ccy: 'NOK', decimals:2, symbol:'kr',  flag:'country/NOK.png'}, 
    {ccy: 'NZD', decimals:2, symbol:'$',   flag:'country/NZD.png'},
    {ccy: 'AFN', decimals:2, symbol:'',    flag:''},
    {ccy: 'ALL', decimals:2, symbol:'',    flag:''},
    {ccy: 'DZD', decimals:2, symbol:'',    flag:''},
    {ccy: 'AOA', decimals:2, symbol:'',    flag:''},
    {ccy: 'ARS', decimals:2, symbol:'',    flag:''},
    {ccy: 'AMD', decimals:2, symbol:'',    flag:''},
    {ccy: 'AWG', decimals:2, symbol:'',    flag:''},
    {ccy: 'AZN', decimals:2, symbol:'',    flag:''},
    {ccy: 'BSD', decimals:2, symbol:'',    flag:''},
    {ccy: 'BHD', decimals:2, symbol:'',    flag:''},
    {ccy: 'BDT', decimals:2, symbol:'',    flag:''},
    {ccy: 'BBD', decimals:2, symbol:'',    flag:''},
    {ccy: 'BYN', decimals:2, symbol:'',    flag:''},
    {ccy: 'BZD', decimals:2, symbol:'',    flag:''},
    {ccy: 'BMD', decimals:2, symbol:'',    flag:''},
    {ccy: 'INR', decimals:2, symbol:'',    flag:''},
    {ccy: 'BTN', decimals:2, symbol:'',    flag:''},
    {ccy: 'BOB', decimals:2, symbol:'',    flag:''},
    {ccy: 'BOV', decimals:2, symbol:'',    flag:''},
    {ccy: 'BAM', decimals:2, symbol:'',    flag:''},
    {ccy: 'BWP', decimals:2, symbol:'',    flag:''},
    {ccy: 'BRL', decimals:2, symbol:'',    flag:''},
    {ccy: 'BND', decimals:2, symbol:'',    flag:''},
    {ccy: 'BGN', decimals:2, symbol:'',    flag:''},
    {ccy: 'XOF', decimals:2, symbol:'',    flag:''},
    {ccy: 'BIF', decimals:2, symbol:'',    flag:''},
    {ccy: 'CVE', decimals:2, symbol:'',    flag:''},
    {ccy: 'KHR', decimals:2, symbol:'',    flag:''},
    {ccy: 'XAF', decimals:2, symbol:'',    flag:''},
    {ccy: 'KYD', decimals:2, symbol:'',    flag:''},
    {ccy: 'CLP', decimals:2, symbol:'',    flag:''},
    {ccy: 'CLF', decimals:2, symbol:'',    flag:''},
    {ccy: 'COP', decimals:2, symbol:'',    flag:''},
    {ccy: 'COU', decimals:2, symbol:'',    flag:''},
    {ccy: 'KMF', decimals:2, symbol:'',    flag:''},
    {ccy: 'CDF', decimals:2, symbol:'',    flag:''},
    {ccy: 'CRC', decimals:2, symbol:'',    flag:''},
    {ccy: 'HRK', decimals:2, symbol:'',    flag:''},
    {ccy: 'CUP', decimals:2, symbol:'',    flag:''},
    {ccy: 'CUC', decimals:2, symbol:'',    flag:''},
    {ccy: 'ANG', decimals:2, symbol:'',    flag:''},
    {ccy: 'DJF', decimals:2, symbol:'',    flag:''},
    {ccy: 'XCD', decimals:2, symbol:'',    flag:''},
    {ccy: 'DOP', decimals:2, symbol:'',    flag:''},
    {ccy: 'EGP', decimals:2, symbol:'',    flag:''},
    {ccy: 'SVC', decimals:2, symbol:'',    flag:''},
    {ccy: 'ERN', decimals:2, symbol:'',    flag:''},
    {ccy: 'SZL', decimals:2, symbol:'',    flag:''},
    {ccy: 'ETB', decimals:2, symbol:'',    flag:''},
    {ccy: 'FKP', decimals:2, symbol:'',    flag:''},
    {ccy: 'FJD', decimals:2, symbol:'',    flag:''},
    {ccy: 'GMD', decimals:2, symbol:'',    flag:''},
    {ccy: 'GEL', decimals:2, symbol:'',    flag:''},
    {ccy: 'GHS', decimals:2, symbol:'',    flag:''},
    {ccy: 'GIP', decimals:2, symbol:'',    flag:''},
    {ccy: 'GTQ', decimals:2, symbol:'',    flag:''},
    {ccy: 'GNF', decimals:2, symbol:'',    flag:''},
    {ccy: 'GYD', decimals:2, symbol:'',    flag:''},
    {ccy: 'HTG', decimals:2, symbol:'',    flag:''},
    {ccy: 'HNL', decimals:2, symbol:'',    flag:''},
    {ccy: 'HKD', decimals:2, symbol:'',    flag:''},
    {ccy: 'HUF', decimals:2, symbol:'',    flag:''},
    {ccy: 'ISK', decimals:2, symbol:'',    flag:''},
    {ccy: 'IDR', decimals:2, symbol:'',    flag:''},
    {ccy: 'XDR', decimals:2, symbol:'',    flag:''},
    {ccy: 'IRR', decimals:2, symbol:'',    flag:''},
    {ccy: 'IQD', decimals:2, symbol:'',    flag:''},
    {ccy: 'ILS', decimals:2, symbol:'',    flag:''},
    {ccy: 'JMD', decimals:2, symbol:'',    flag:''},
    {ccy: 'JOD', decimals:2, symbol:'',    flag:''},
    {ccy: 'KZT', decimals:2, symbol:'',    flag:''},
    {ccy: 'KES', decimals:2, symbol:'',    flag:''},
    {ccy: 'KPW', decimals:2, symbol:'',    flag:''},
    {ccy: 'KRW', decimals:2, symbol:'',    flag:''},
    {ccy: 'KWD', decimals:2, symbol:'',    flag:''},
    {ccy: 'KGS', decimals:2, symbol:'',    flag:''},
    {ccy: 'LAK', decimals:2, symbol:'',    flag:''},
    {ccy: 'LBP', decimals:2, symbol:'',    flag:''},
    {ccy: 'LSL', decimals:2, symbol:'',    flag:''},
    {ccy: 'LRD', decimals:2, symbol:'',    flag:''},
    {ccy: 'LYD', decimals:2, symbol:'',    flag:''},
    {ccy: 'MOP', decimals:2, symbol:'',    flag:''},
    {ccy: 'MKD', decimals:2, symbol:'',    flag:''},
    {ccy: 'MGA', decimals:2, symbol:'',    flag:''},
    {ccy: 'MWK', decimals:2, symbol:'',    flag:''},
    {ccy: 'MYR', decimals:2, symbol:'',    flag:''},
    {ccy: 'MVR', decimals:2, symbol:'',    flag:''},
    {ccy: 'MRU', decimals:2, symbol:'',    flag:''},
    {ccy: 'MUR', decimals:2, symbol:'',    flag:''},
    {ccy: 'XUA', decimals:2, symbol:'',    flag:''},
    {ccy: 'MXN', decimals:2, symbol:'',    flag:''},
    {ccy: 'MXV', decimals:2, symbol:'',    flag:''},
    {ccy: 'MDL', decimals:2, symbol:'',    flag:''},
    {ccy: 'MNT', decimals:2, symbol:'',    flag:''},
    {ccy: 'MAD', decimals:2, symbol:'',    flag:''},
    {ccy: 'MZN', decimals:2, symbol:'',    flag:''},
    {ccy: 'MMK', decimals:2, symbol:'',    flag:''},
    {ccy: 'NAD', decimals:2, symbol:'',    flag:''},
    {ccy: 'NPR', decimals:2, symbol:'',    flag:''},
    {ccy: 'XPF', decimals:2, symbol:'',    flag:''},
    {ccy: 'NIO', decimals:2, symbol:'',    flag:''},
    {ccy: 'NGN', decimals:2, symbol:'',    flag:''},
    {ccy: 'OMR', decimals:2, symbol:'',    flag:''},
    {ccy: 'PKR', decimals:2, symbol:'',    flag:''},
    {ccy: 'PAB', decimals:2, symbol:'',    flag:''},
    {ccy: 'PGK', decimals:2, symbol:'',    flag:''},
    {ccy: 'PYG', decimals:2, symbol:'',    flag:''},
    {ccy: 'PEN', decimals:2, symbol:'',    flag:''},
    {ccy: 'PHP', decimals:2, symbol:'',    flag:''},
    {ccy: 'PLN', decimals:2, symbol:'',    flag:''},
    {ccy: 'QAR', decimals:2, symbol:'',    flag:''},
    {ccy: 'RON', decimals:2, symbol:'',    flag:''},
    {ccy: 'RUB', decimals:2, symbol:'',    flag:''},
    {ccy: 'RWF', decimals:2, symbol:'',    flag:''},
    {ccy: 'SHP', decimals:2, symbol:'',    flag:''},
    {ccy: 'WST', decimals:2, symbol:'',    flag:''},
    {ccy: 'STN', decimals:2, symbol:'',    flag:''},
    {ccy: 'SAR', decimals:2, symbol:'',    flag:''},
    {ccy: 'RSD', decimals:2, symbol:'',    flag:''},
    {ccy: 'SCR', decimals:2, symbol:'',    flag:''},
    {ccy: 'SLL', decimals:2, symbol:'',    flag:''},
    {ccy: 'SGD', decimals:2, symbol:'',    flag:''},
    {ccy: 'XSU', decimals:2, symbol:'',    flag:''},
    {ccy: 'SBD', decimals:2, symbol:'',    flag:''},
    {ccy: 'SOS', decimals:2, symbol:'',    flag:''},
    {ccy: 'ZAR', decimals:2, symbol:'',    flag:''},
    {ccy: 'SSP', decimals:2, symbol:'',    flag:''},
    {ccy: 'LKR', decimals:2, symbol:'',    flag:''},
    {ccy: 'SDG', decimals:2, symbol:'',    flag:''},
    {ccy: 'SRD', decimals:2, symbol:'',    flag:''},
    {ccy: 'SEK', decimals:2, symbol:'',    flag:''},
    {ccy: 'CHF', decimals:2, symbol:'',    flag:''},
    {ccy: 'CHE', decimals:2, symbol:'',    flag:''},
    {ccy: 'CHW', decimals:2, symbol:'',    flag:''},
    {ccy: 'SYP', decimals:2, symbol:'',    flag:''},
    {ccy: 'TWD', decimals:2, symbol:'',    flag:''},
    {ccy: 'TJS', decimals:2, symbol:'',    flag:''},
    {ccy: 'TZS', decimals:2, symbol:'',    flag:''},
    {ccy: 'THB', decimals:2, symbol:'',    flag:''},
    {ccy: 'TOP', decimals:2, symbol:'',    flag:''},
    {ccy: 'TTD', decimals:2, symbol:'',    flag:''},
    {ccy: 'TND', decimals:2, symbol:'',    flag:''},
    {ccy: 'TRY', decimals:2, symbol:'',    flag:''},
    {ccy: 'TMT', decimals:2, symbol:'',    flag:''},
    {ccy: 'UGX', decimals:2, symbol:'',    flag:''},
    {ccy: 'UAH', decimals:2, symbol:'',    flag:''},
    {ccy: 'AED', decimals:2, symbol:'',    flag:''},
    {ccy: 'USN', decimals:2, symbol:'',    flag:''},
    {ccy: 'UYU', decimals:2, symbol:'',    flag:''},
    {ccy: 'UYI', decimals:2, symbol:'',    flag:''},
    {ccy: 'UYW', decimals:2, symbol:'',    flag:''},
    {ccy: 'UZS', decimals:2, symbol:'',    flag:''},
    {ccy: 'VUV', decimals:2, symbol:'',    flag:''},
    {ccy: 'VES', decimals:2, symbol:'',    flag:''},
    {ccy: 'VED', decimals:2, symbol:'',    flag:''},
    {ccy: 'VND', decimals:2, symbol:'',    flag:''},
    {ccy: 'YER', decimals:2, symbol:'',    flag:''},
    {ccy: 'ZMW', decimals:2, symbol:'',    flag:''},
    {ccy: 'ZWL', decimals:2, symbol:'',    flag:''},
    {ccy: 'XBA', decimals:2, symbol:'',    flag:''},
    {ccy: 'XBB', decimals:2, symbol:'',    flag:''},
    {ccy: 'XBC', decimals:2, symbol:'',    flag:''},
    {ccy: 'XBD', decimals:2, symbol:'',    flag:''},
    {ccy: 'XTS', decimals:2, symbol:'',    flag:''},
    {ccy: 'XXX', decimals:2, symbol:'',    flag:''},
    {ccy: 'XAU', decimals:2, symbol:'',    flag:''},
    {ccy: 'XPD', decimals:2, symbol:'',    flag:''},
    {ccy: 'XPT', decimals:2, symbol:'',    flag:''},
    {ccy: 'XAG', decimals:2, symbol:'',    flag:''} 
]

export const CONVERSION_RATES = [
    {base: 'AUD', terms: 'USD', rate:0.8371  },
    {base: 'CAD', terms: 'USD', rate:0.8711  },
    {base: 'USD', terms: 'CNY', rate:6.1715  },
    {base: 'EUR', terms: 'USD', rate:1.2315  },
    {base: 'GBP', terms: 'USD', rate:1.5683  },
    {base: 'NZD', terms: 'USD', rate:0.7750  },
    {base: 'USD', terms: 'JPY', rate:119.95  },
    {base: 'EUR', terms: 'CZK', rate:27.6028 }, 
    {base: 'EUR', terms: 'DKK', rate:7.4405  },
    {base: 'EUR', terms: 'NOK', rate:8.6651  },
]


export const calculateRate = (fromCurrency, toCurrency) => {
    let termsArr = CROSS_VIA_MARTIX.find(x => x.base === fromCurrency).terms
    let relation = (termsArr.find( x => x.ccy === toCurrency)).relation
    if (relation === 'DDD') {
      return CONVERSION_RATES.find( x => x.base === fromCurrency && x.terms === toCurrency).rate 
    }
    if (relation === 'INV') {
      return 1 / CONVERSION_RATES.find( x => x.base === toCurrency && x.terms === fromCurrency).rate 
    }
    if (relation === '1:1') {
        return 1
    }
    if (relation === 'EUR' || relation === 'USD') {
        return calculateRate(fromCurrency,relation) * calculateRate(relation, toCurrency)
    }
  }


  export const isValidCurrencyPair = (state) => {
    return ( CROSS_VIA_MARTIX.find(x => x.base === state.termsCurrency) === undefined 
    || CROSS_VIA_MARTIX.find(x => x.base === state.baseCurrency) === undefined || state.termsCurrency.length < 3  ? false : true)
  }